version: '3'

env:
  DIR_SCRIPTS: "./"
  DIR_LOGS: "./../logs"

tasks:

  default:
    silent: true
    cmd: task --list
  
  log:test:
    desc: Run test for log functions
    cmds:
      - source ./logs.sh && test

  helm:upload:
    desc: Upload helm charts
    vars:
      chart_prefix: "charts/"
    requires:
      vars:
        - env
    cmd: ./helm.sh {{.env}} {{.chart_prefix}}

  container:upload:
    desc: Upload containers
    requires:
      vars:
        - configs
    cmd: ./container.sh {{.configs}}

  container:test:
    desc: Test container Upload
    cmds:
      - task: container:upload
        vars:
          configs: ./../example
