version: '3'

env:
  DIR_SCRIPTS: "./"
  DIR_LOGS: "./../logs"

vars:
  example_dir: "./../example"

tasks:

  default:
    silent: true
    cmd: task --list
  
  log:test:
    desc: Run test for log functions
    cmds:
      - source ./logs.sh && test {{.DIR_LOGS}}

  helm:upload:
    desc: Upload helm charts
    vars:
      chart_prefix: "charts/"
    requires:
      vars:
        - configs
    cmd: ./helm.sh {{.configs}} {{.chart_prefix}}
  
  helm:test:
    desc: Test helm charts upload
    cmds: 
      - task: helm:upload
        vars:
          chart_prefix: "charts/"
          configs: "{{.example_dir}}"

  container:upload:
    desc: Upload containers
    requires:
      vars:
        - configs
    cmd: ./container.sh {{.configs}}

  container:test:
    desc: Test container upload
    cmds:
      - task: container:upload
        vars:
          configs: "{{.example_dir}}"
